name: sellerproof
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  vosk_flutter: ^0.3.48
  archive: ^3.6.1
  camera: ^0.10.5+5
  provider: ^6.1.1
  mobile_scanner: ^7.1.3
  flutter_tts: ^4.2.3
  shared_preferences: ^2.3.3
  file_picker: ^8.1.6
  permission_handler: ^11.0.1
  dio: ^5.9.0
dependency_overrides:
  vosk_flutter:
    git:
      url: https://github.com/alphacep/vosk-flutter.git
      ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/models/vosk-model-small-ru-0.22.zip
